[versions]
minecraft = "1.18.2"
quilt_mappings = "1.18.2+build.26"
fabric_loader = "0.14.14"
fabric_api = "0.67.1+1.18.2"
midnightlib = "0.4.4"
modmenu = "3.2.5"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }

fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
midnightlib = { module = "maven.modrinth:midnightlib", version.ref = "midnightlib" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]

[plugins]
